### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by cir-lab** [YuxiangCui/model-based-social-navigation#1]
Dear author, we plan to use your code for training, but during the training process we found that the model-based method has very poor training results, it can barely complete the full campaign and it gets stuck after a while, is it our configuration problem?

**Comment by YuxiangCui** [comment]
Thank you for your issue report. The model-based version normally takes fewer env steps but more training times, so maybe the training procedure has not ended yet according to your description. Training curves in the paper can be referred to as an example. Pre-trained policy models and world models are provided in the repository for you to speed up the training.

**Comment by cir-lab** [comment]
Thank you for your reply. During the training process, we noticed that the model-based training would get stuck within a few minutes and stop training. Is it because we don't have enough hardware? We have recorded a video and hope to send you the details by email, I would appreciate it if you could give me the your email address

**Comment by YuxiangCui** [comment]
If by ‘stuck’ you mean the training procedure rather than the actual robots, maybe you should pay attention to the error reports and figure out the breakpoint. Feel free to contact me. yuxiangcui@zju.edu.cn

**Comment by YuxiangCui** [comment]
Not updated for a long time. Closing this issue.
