### ISSUE TITLE
Does the method need location？

### ISSUE THREAD

**Issue by Watson52** [YuxiangCui/model-based-social-navigation#2]
Hi, I am new to learn social navigation. I want to know does it need ability of location? Or how to let the robot achieve the goal place in the real world experiments?
Your answer will be greatly appreciated.

**Comment by YuxiangCui** [comment]
The robots should be able to know the relative positions of the goals, and then they can gradually approach their own goals while avoiding collisions. The relative goal position can be obtained through localization methods like SLAM or some other sensors like UWB in real-world experiments, depending on whether you have got a global map before the experiments or not.

**Comment by Watson52** [comment]
你的邮件我已经收到~辛苦啦~

**Comment by Watson52** [comment]
> The robots should be able to know the relative positions of the goals, and then they can gradually approach their own goals while avoiding collisions. The relative goal position can be obtained through localization methods like SLAM or some other sensors like UWB in real-world experiments, depending on whether you have got a global map before the experiments or not.

thanks! I got it.
